TOOL-11707 Install Java 11 on DCoL hosts
delphix/appliance-build pull request #576
Opened 2021-07-27 20:02 UTC by blim747

DCoL hosts are Jenkins agents and therefore has a Java 8 JDK installed (cf. [`appliance-build.dcenter`](https://github.com/delphix/appliance-build/blob/be1ecc9701ca18b05dec0ec6b6016bb39bc79b6c/live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml#L21)). In the coming months, the Jenkins project will start to recommend users move off Java 8 and to Java 11. With the move to Java 11, we need to also add a Java 11 JDK.

Note: `adoptopenjdk-java11-jdk` is technically before `adoptopenjdk-java8-jdk` alphabetically

2021-07-27 23:11 UTC, basil reviewed
Have you been able to confirm that this PR works for its stated purpose—that given an appliance built from this PR, Jenkins can establish an agent connection using Java 11?

2021-07-28 00:24 UTC, blim747 commented
@basil , how would you suggest I test this?

I'm thinking I can run a custom appliance-build job with a custom appliance-build git URL and branch, but I'm stuck on how can I apply the build to dcol-dev without impacting the production dcenter variant images

2021-07-28 00:46 UTC, basil commented
I suggest you take a look at other pull requests that have been merged and consider how those were tested. They generally use `git ab-pre-push`, which runs a Jenkins pipeline that builds the appliance image and imports it into DCenter, from which you can clone a VM and test that it is as you expect.

---

When modifying code, it is generally the developer's responsibility to test the modified code before requesting a review. The reviewer's responsibility is to determine _whether_ sufficient testing has been performed; it is not the reviewer's responsibility to determine _how_ to test the code. More explicitly, determining how to test modified code is part of the development process. If you have not yet determined how to test this code, then this change is not yet ready for review.

2021-07-30 06:24 UTC, blim747 commented
I've tested this change out and it works. On my dcol2 VM:
```
delphix@blim-t11707-try2:~$ cd /usr/lib/jvm
delphix@blim-t11707-try2:/usr/lib/jvm$ ls
adoptopenjdk-11-hotspot-amd64  adoptopenjdk-java8-jdk-amd64
delphix@blim-t11707-try2:/usr/lib/jvm$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
delphix@blim-t11707-try2:/usr/lib/jvm$ sudo update-alternatives --display java
java - manual mode
  link best version is /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin/java
  link currently points to /usr/lib/jvm/adoptopenjdk-java8-jdk-amd64/bin/java
  link java is /usr/bin/java
  slave java.1 is /usr/share/man/man1/java.1
/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin/java - priority 1111
  slave java.1: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/man/man1/java.1
/usr/lib/jvm/adoptopenjdk-java8-jdk-amd64/bin/java - priority 318
```

I'm verbosely documenting my journey for how I was able to test this change for future reference.

I spent a good amount of time trying to figure out how to test it since `git ab-pre-push` does not support building the `internal-dcenter` variant. The `internal-dcenter` variant is only an option on nightly appliance build jobs.

I was ultimately able to build the image by manually setting the parameters of the [appliance-build master nightly job](http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/nightly/) and setting the APPLIANCE_BUILD_GIT_URL to my fork and the branch to my custom branch. I also only built the `internal-dcenter` variant for the esx platform.

With that said, several builds failed. This was the time I experimented with various combinations of packages and Ansible settings. Originally I tried to install `openjdk-11-jdk` but my Ansible role kept failing during the apt install step with this blob of error having to do with ca-certificates not being able to write.

```
18:37:05  task path: /var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/post-push/appliance-build/live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml:51
18:38:15  FAILED - RETRYING: appliance-build.dcenter : apt (3 retries left).
18:39:53  FAILED - RETRYING: appliance-build.dcenter : apt (2 retries left).
18:41:32  FAILED - RETRYING: appliance-build.dcenter : apt (1 retries left).
18:43:26  fatal: [binary]: FAILED! => {"attempts": 3, "cache_update_time": 1627609377, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'openjdk-11-jdk-headless'' failed: E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)\nhead: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory\nthe keytool command requires a mounted proc fs (/proc).\ndpkg: error processing package ca-certificates-java (--configure):\n installed ca-certificates-java package post-installation script subprocess returned error exit status 1\ndpkg: dependency problems prevent configuration of openjdk-11-jre-headless:amd64:\n openjdk-11-jre-headless:amd64 depends on ca-certificates-java; however:\n  Package ca-certificates-java is not configured yet.\n\ndpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):\n dependency problems - leaving unconfigured\ndpkg: dependency problems prevent configuration of openjdk-11-jdk-headless:amd64:\n openjdk-11-jdk-headless:amd64 depends on openjdk-11-jre-headless (= 11.0.11+9-0ubuntu2~18.04); however:\n  Package openjdk-11-jre-headless:amd64 is not configured yet.\n\ndpkg: error processing package openjdk-11-jdk-headless:amd64 (--configure):\n dependency problems - leaving unconfigured\nthe keytool command requires a mounted proc fs (/proc).\nErrors were encountered while processing:\n ca-certificates-java\n openjdk-11-jre-headless:amd64\n openjdk-11-jdk-headless:amd64\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)\nhead: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory\nthe keytool command requires a mounted proc fs (/proc).\ndpkg: error processing package ca-certificates-java (--configure):\n installed ca-certificates-java package post-installation script subprocess returned error exit status 1\ndpkg: dependency problems prevent configuration of openjdk-11-jre-headless:amd64:\n openjdk-11-jre-headless:amd64 depends on ca-certificates-java; however:\n  Package ca-certificates-java is not configured yet.\n\ndpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):\n dependency problems - leaving unconfigured\ndpkg: dependency problems prevent configuration of openjdk-11-jdk-headless:amd64:\n openjdk-11-jdk-headless:amd64 depends on openjdk-11-jre-headless (= 11.0.11+9-0ubuntu2~18.04); however:\n  Package openjdk-11-jre-headless:amd64 is not configured yet.\n\ndpkg: error processing package openjdk-11-jdk-headless:amd64 (--configure):\n dependency problems - leaving unconfigured\nthe keytool command requires a mounted proc fs (/proc).\nErrors were encountered while processing:\n ca-certificates-java\n openjdk-11-jre-headless:amd64\n openjdk-11-jdk-headless:amd64\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)", "head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory", "the keytool command requires a mounted proc fs (/proc).", "dpkg: error processing package ca-certificates-java (--configure):", " installed ca-certificates-java package post-installation script subprocess returned error exit status 1", "dpkg: dependency problems prevent configuration of openjdk-11-jre-headless:amd64:", " openjdk-11-jre-headless:amd64 depends on ca-certificates-java; however:", "  Package ca-certificates-java is not configured yet.", "", "dpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):", " dependency problems - leaving unconfigured", "dpkg: dependency problems prevent configuration of openjdk-11-jdk-headless:amd64:", " openjdk-11-jdk-headless:amd64 depends on openjdk-11-jre-headless (= 11.0.11+9-0ubuntu2~18.04); however:", "  Package openjdk-11-jre-headless:amd64 is not configured yet.", "", "dpkg: error processing package openjdk-11-jdk-headless:amd64 (--configure):", " dependency problems - leaving unconfigured", "the keytool command requires a mounted proc fs (/proc).", "Errors were encountered while processing:", " ca-certificates-java", " openjdk-11-jre-headless:amd64", " openjdk-11-jdk-headless:amd64", "E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nopenjdk-11-jdk-headless is already the newest version (11.0.11+9-0ubuntu2~18.04).\n0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.\n3 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up ca-certificates-java (20180516ubuntu1~18.04.1) ...\nProcessing triggers for ca-certificates (20210119~18.04.1) ...\nUpdating certificates in /etc/ssl/certs...\n0 added, 0 removed; done.\nRunning hooks in /etc/ca-certificates/update.d...\n\nE: /etc/ca-certificates/update.d/jks-keystore exited with code 1.\ndone.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "openjdk-11-jdk-headless is already the newest version (11.0.11+9-0ubuntu2~18.04).", "0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.", "3 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up ca-certificates-java (20180516ubuntu1~18.04.1) ...", "P [...]

2021-07-30 14:39 UTC, basil requested changes
> `git ab-pre-push` does not support building the internal-dcenter variant

The "Testing Done" section of previous PRs would indicate otherwise.

> my Ansible role kept failing during the `apt install` step with this blob of error

Try adding `ca-certificates-java` to [the list of packages that `delphix-platform` depends on](https://github.com/delphix/delphix-platform/blob/add13a916377fd025a4c430dcdefc42c209aa95b/debian/rules) so that it gets installed earlier on in the build during the `lb_chroot_archives chroot install` phase, where `/proc` is mounted.

2021-07-30 22:30 UTC, blim747 commented
Happy to say @basil's suggestion to add `ca-certificates-java` to delphix-platform worked:
```
delphix@blim-t11707-try3:/usr/lib/jvm$ ls
adoptopenjdk-java8-jdk-amd64  java-1.11.0-openjdk-amd64  java-11-openjdk-amd64
delphix@blim-t11707-try3:/usr/lib/jvm$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
delphix@blim-t11707-try3:/usr/lib/jvm$ sudo update-alternatives --display java
java - manual mode
  link best version is /usr/lib/jvm/java-11-openjdk-amd64/bin/java
  link currently points to /usr/lib/jvm/adoptopenjdk-java8-jdk-amd64/bin/java
  link java is /usr/bin/java
  slave java.1.gz is /usr/share/man/man1/java.1.gz
/usr/lib/jvm/adoptopenjdk-java8-jdk-amd64/bin/java - priority 318
/usr/lib/jvm/java-11-openjdk-amd64/bin/java - priority 1111
  slave java.1.gz: /usr/lib/jvm/java-11-openjdk-amd64/man/man1/java.1.gz
delphix@blim-t11707-try3:/usr/lib/jvm$
```

Here's associated delphix-platform PR: https://github.com/delphix/delphix-platform/pull/317

appliance-build-orchestrator-pre-push job: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1078/console
The post-push job that built internal-dcenter-esx.ova: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/post-push/116208/, the build lives at s3://dev-de-images/builds/jenkins-ops/devops-gate/master/appliance-build/master/pre-push/845/internal-dcenter-esx/internal-dcenter-esx.ova on S3
Due to the internal-dev variant taking a while to build, I manually imported the image into a DCoL VM here: http://collins.d.delphix.com:28565/job/devops-gate/job/tool-11959-default-esx-credential/job/sync-ova-into-dcenter/1/console

2021-08-09 16:03 UTC, basil commented
Closing in favor of #582.

2021-08-09 16:03 UTC, closed without merging