Ubuntu 24.04 POC
delphix/appliance-build pull request #769
Opened 2024-08-20 20:07 UTC by palash-gandhi

<details open>
<summary><h2> Problem </h2></summary>

Provide a clear description of the high-level problem you are trying to
solve. The problem statement should be written in terms of a specific
symptom that affects users or the business. The problem statement should
not be written in terms of the solution. If possible, include a minimal
reproducible example (MRE) with steps to reproduce, expected results,
and actual results.
</details>

<details open>
<summary><h2> Solution </h2></summary>

Provide a clear description of the high-level solution you have chosen.
If there were other possible solutions that you considered and rejected,
mention those along with the corresponding reasoning. Do not describe
implementation details when writing about the solution; these should go
into the implementation section instead.
</details>

<details>
<summary><h2> Testing Done </h2></summary>

Provide a clear description of how this change was tested. At minimum
this should include proof that a computer has executed the changed
lines. Ideally this should include an automated test or an explanation
as to why this pull request has no tests.
</details>

2025-01-14 21:08 UTC, sebroy requested changes

2025-01-14 21:08 UTC, sebroy commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +      - openjdk-8-jdk
should we be using the `-headless` package here?

2025-01-14 21:08 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml
> +      - openjdk-8-jdk
I think we want the headless JDK here. Also, why do we need this here and in the bootstrap ansible role? Same question goes for all of the other packages duplicated here. This is more of a question for @prakashsurya .

2025-01-14 21:08 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
> +      - openjdk-8-jdk
This should be headless.

2025-01-14 21:08 UTC, sebroy commented on live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot
> +openjdk-8-jdk
This should be headless.

2025-01-14 23:29 UTC, prakashsurya commented on live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml
> +      - openjdk-8-jdk
the bootstrap role configures the build server.. i.e. the VM we use to run appliance-build..

this role configures the build server VM image we use for various builds..

if the implication is that we should just configure the build server to have all necessary dependencies pre-installed, via here.. and then we don't need the bootstrap configuration.. that design could work, but this role would need to know the dependencies of all builds that'll occur on the image, to ensure they're all pre-installed..

I think the reason we pre-install java specifically here, is only due to our Jenkins infrastructure needed a Java runtime to connect the build VM as a Jenkins slave (i.e. the VM image needs to have ssh and java for Jenkins to connect with it).. it's not being installed due to it being needed to run any repo's build system.. the overlap between Jenkins and appliance-build's dependencies is just coincidental..

i.e. this role is just the bare minimum to enable the build VM to be used in Jenkins.. the bootstrap role is to install w/e build dependencies are needed to run w/e build is being performed..

hope that makes sense..?

2025-01-15 06:32 UTC, palash-gandhi commented on live-build/variants/internal-dcenter/package-lists/dcenter.list.chroot
> +openjdk-8-jdk
done

2025-01-15 06:32 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.unittest-internal/tasks/main.yml
> +      - openjdk-8-jdk
done

2025-01-15 06:32 UTC, palash-gandhi commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +      - openjdk-8-jdk
done

2025-01-15 19:23 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml
> +      - openjdk-8-jdk
@sebroy Can I mark this as resolved?

2025-01-15 21:07 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.buildserver-internal/tasks/main.yml
> +      - openjdk-8-jdk
Yep, this makes sense.

2025-01-15 21:12 UTC, sebroy requested changes

2025-01-15 21:12 UTC, sebroy commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +    purge: true
I'm wondering how this gets installed to begin with...

2025-01-15 21:12 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
> +    - { regexp: "^RPCMOUNTDOPTS=", line: 'RPCMOUNTDOPTS="--num-threads=5 --manage-gids"' }
24.04 no longer references the `/etc/default/nfs-kernel-server` file.

2025-01-15 22:37 UTC, palash-gandhi commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +    purge: true
Marking as resolved per our Slack conversation:


> Palash Gandhi
>   1:10 PM
> It's not installed on the engine:
> delphix@localhost:~$ dpkg -l | grep unattended
> delphix@localhost:~$
> But it does exist within the bootstrap-24.04 image that is a temporary buildserver sourced from Ubuntu till we have an os-upgrade buildserver
> 
> 
> Sebastien Roy
>   1:12 PM
> Got it, so when we switch to our own build server, we'll no longer need that ansible task (or, it will be a no-op)? (edited) 
> 
> 
> Palash Gandhi
>   1:15 PM
> Correct, it will be a no-op, but I'd still rather leave it there for future LTS upgrades. Each LTS upgrade will likely begin with sourcing an Ubuntu image first & thus will require uninstall unattended-upgrades. This will minimize the manual tasks required to bootstrap future LTS upgrade projects..

2025-01-15 22:38 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
> +    - { regexp: "^RPCMOUNTDOPTS=", line: 'RPCMOUNTDOPTS="--num-threads=5 --manage-gids"' }
Great catch, thanks.

2025-01-16 05:53 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
> +    - { regexp: "^RPCMOUNTDOPTS=", line: 'RPCMOUNTDOPTS="--num-threads=5 --manage-gids"' }
Fixed

2025-01-20 17:34 UTC, prakashsurya approved these changes
looks reasonable.. curious about the changes to the bootstrap role, though..

2025-01-20 17:34 UTC, prakashsurya commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +      # The VSDK plugin requires python3.11
why does the VSDK requirements change the appliance-build's build requirements? IIRC, this configuration is to install the necessary packages to run appliance-build, not a DE's runtime requirements..

2025-01-20 17:34 UTC, prakashsurya commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +- name: Stop unattended-upgrades systemd service in preparation for package removal
why do we need this now, when we haven't needed it in the past?

2025-01-20 17:34 UTC, prakashsurya commented on scripts/run-live-build.sh
> +check_env DELPHIX_PACKAGE_MIRROR_MAIN DELPHIX_PACKAGE_MIRROR_SECONDARY
does this mean, when running manually, the user needs to pass in these environment variables now, when previously we didn't have to?

I'm not strictly opposed to this, but it does make it more difficult to run manually when that workflow is desired.

At one point, we could run it manually with no parameters and it'd auto-determine the correct values, and we keep regressing on that functionality.. which is fine, I guess, but makes it harder on some workflows that need to run this manually for debugging (e.g. build failures, etc.).

2025-01-21 22:21 UTC, palash-gandhi commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +      # The VSDK plugin requires python3.11
This is not a runtime requirement. To build the virtualization package i.e. the gradle task of the app-gate requires python3.11

2025-01-21 22:23 UTC, palash-gandhi commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +- name: Stop unattended-upgrades systemd service in preparation for package removal
I used this role to bootstrap a vanilla Ubuntu image to use as a temporary build server till a DE-based buildserver is built.
From a recent slack conversation about this:

> Sebastien Roy
> [1:08 PM](https://perforce.slack.com/archives/C07HY8FURB4/p1736975290891139)
> [@Palash Gandhi](https://perforce.slack.com/team/U06SB34AGVA)
>  How was unattended-upgrades installed to begin with? Is that erroneously installed on the engine as well?
> 
> 
> Palash Gandhi
>   1:10 PM
> It's not installed on the engine:
> delphix@localhost:~$ dpkg -l | grep unattended
> delphix@localhost:~$
> But it does exist within the bootstrap-24.04 image that is a temporary buildserver sourced from Ubuntu till we have an os-upgrade buildserver
> 
> 
> Sebastien Roy
> [1:12 PM](https://perforce.slack.com/archives/C07HY8FURB4/p1736975574815659)
> Got it, so when we switch to our own build server, we'll no longer need that ansible task (or, it will be a no-op)? 
> 
> 
> Palash Gandhi
>   1:15 PM
> Correct, it will be a no-op, but I'd still rather leave it there for future LTS upgrades. Each LTS upgrade will likely begin with sourcing an Ubuntu image first & thus will require uninstall unattended-upgrades. This will minimize the manual tasks required to bootstrap future LTS upgrade projects..

2025-01-21 22:26 UTC, palash-gandhi commented on scripts/run-live-build.sh
> +check_env DELPHIX_PACKAGE_MIRROR_MAIN DELPHIX_PACKAGE_MIRROR_SECONDARY
Yes, running manually will require these params to be set. There are now 2 sets of mirrors: v1 & v2. While we could infer this if an upstream branch is set and then decide which mirror to use, I'd rather perform this check here to ensure that this is set by all of our build automation (which already sets these afaict).
I have never had to use the manual workflow and hence assumed that it's not common.

2025-01-21 23:02 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
> +    mode: 0444
looks like we need to clean this up?

2025-01-22 18:39 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.virtualization-common/tasks/main.yml
> +    mode: 0444
removed

2025-01-22 20:28 UTC, sebroy approved these changes

2025-01-22 20:28 UTC, sebroy commented on live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
> +    masked: true
Minor nit: Can you combine these three tasks by using the `with_items` ansible construct?

2025-01-22 21:26 UTC, palash-gandhi commented on live-build/misc/ansible-roles/appliance-build.dcenter/tasks/main.yml
> +    masked: true
done

2025-01-22 21:26 UTC, merged

2025-01-23 19:27 UTC, prakashsurya commented on bootstrap/roles/appliance-build.bootstrap/tasks/main.yml
> +      # The VSDK plugin requires python3.11
> To build the virtualization package i.e. the gradle task of the app-gate requires python3.11

we don't build the virtualization package as part of this repo, though.. is this needed to install the virtualization package?